### ISSUE TITLE
Roadmap to registration

### ISSUE THREAD

**Issue by martinkosch** [martinkosch/Open62541.jl#6]
- [x] Create (minimal) README.md for package
- [x] Create first steps page in documentation with minimal examples
- [x] Clean up documentation (Sphinx comments are currently interpreted as Doxygen comments)
- [x] Make memory usage safe and comprehensible (#8)
- [x] Export only a small set of elementary function as initial API (see. #9)

**Comment by thomvet** [comment]
I am starting to tick things off here (see PR #18).

**Comment by thomvet** [comment]
After reviewing the automatically generated docstrings more closely, the information content of them is really low when seen on top of the open62541 manual. I decided to simply remove them; maybe bringing some better docstrings back later on.

**Comment by thomvet** [comment]
I have just merged https://github.com/martinkosch/open62541.jl/pull/20 and I think the package would be good to go for an initial registration. 

Now, I don't know how to do it (and whether I even have the rights to do it) - Since you seem to have registered packages before, could you take care of it @martinkosch?

**Comment by martinkosch** [comment]
Great, thank you for your work so far! 

I tried to register the package using the Registrator.jl but the registration is blocking due to the lowercase first letter in the package name (https://github.com/JuliaRegistries/General/pull/108878). After having a look though the existing packages in the registry, I assume renaming our package to Open62541.jl is the best option to proceed. 
What do you think?

**Comment by thomvet** [comment]
I agree, uppercase first letter to follow the Julia convention is the best solution. (Julia package should follow Julia convention)

**Comment by martinkosch** [comment]
Open62541.jl is registered 🎉
Closing this issue...

**Comment by thomvet** [comment]
Great!
